[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "echo 'Current directory:' && pwd",
  "echo 'Files in current directory:' && ls -la",
  "echo 'Looking for server.js:' && find . -name 'server.js' -type f",
  "npm ci"
]

[phases.build]
cmds = [
  "echo 'Build phase - Current directory:' && pwd",
  "echo 'Files after install:' && ls -la",
  "echo 'Verifying server.js exists:' && test -f server.js && echo 'server.js found!' || echo 'server.js NOT found!'"
]

[start]
cmd = "node start.js"
